---
- name: install yum-plugin-fastestmirror
  yum:
    name: yum-plugin-fastestmirror
  when: ansible_distribution != 'Debian' and ansible_distribution != 'Ubuntu'

# @see https://github.com/ansible/ansible/issues/30754#issuecomment-367079949
## @see https://askubuntu.com/a/45690
## @see https://askubuntu.com/a/37754
#- name: set mirror list on source list of apt
#  blockinfile:
#    path: /etc/apt/sources.list
#    insertbefore: BOF
#    block: |
#      deb mirror://mirrors.ubuntu.com/mirrors.txt precise main restricted universe multiverse
#      deb mirror://mirrors.ubuntu.com/mirrors.txt precise-updates main restricted universe multiverse
#      deb mirror://mirrors.ubuntu.com/mirrors.txt precise-backports main restricted universe multiverse
#      deb mirror://mirrors.ubuntu.com/mirrors.txt precise-security main restricted universe multiverse
#  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
